[general]
import = [
  "themes/catppuccin-latte.toml"
]

[font]
size = 14.0

[font.normal]
family = "Iosevka Nerd Font"
style = "Regular"

[terminal]
shell = "fish"

[window]
decorations = "None"
decorations_theme_variant = "Light"
opacity = 0.75
